menu:
 首页: /
 文章: /archives
 工具: /to-markdown.html
 关于: /about
 Rss: /atom.xml
 捐助: http://me.alipay.com/zmj1987 

widgets:
- search
- yuan
- category
- tagcloud
- weibo
- blogrolldgets:



excerpt_link: 阅读全文

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

baidu_analytics: true

google_analytics:
rss:

comment_provider: facebook
# Facebook comment
facebook:
  appid: 123456789012345
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light
